### PR TITLE
giuseppe/fix tests

### PR DESCRIPTION
**Pull request by giuseppe**
some trivial fixes

### CODE REVIEW

**Comment by mbarnes** [comment]
Don't know if you want to wait for Colin's feedback, but this looks okay to me.

Where the tests check for UID 0 maybe add a brief comment explaining why?

**Comment by giuseppe** [comment]
thanks for the review.  I have pushed another version that have comments where I check for the user id.  Is it fine for you?

**Comment by mbarnes** [comment]
Yep, :+1: from me.

**Comment by giuseppe** [comment]
thanks, I went ahead and pushed the patches.

**Pull request closed without merging**
