### PR TITLE
deltas: Include an endianness marker

### PR DESCRIPTION
**Pull request by cgwalters**
We screwed up and had delta integers use host endianness.  Start
digging out by at least annotating the endianness.

https://bugzilla.gnome.org/show_bug.cgi?id=762515

### CODE REVIEW

**Comment by alexlarsson** [comment]
Why lowercase 'l' but uppercase 'B' ?

**Comment by cgwalters** [comment]
I think the idea is it's little lowercase, and a big uppercase.  Anyways, it's what DBus uses:
https://dbus.freedesktop.org/doc/dbus-specification.html

```
1st BYTE	Endianness flag; ASCII 'l' for little-endian or ASCII 'B' for big-endian. Both header and body are in this endianness.
```

**Comment by cgwalters** [comment]
This is one of those times where I kind of regret not using Protocol Buffers for this.  Oh well...

**Comment by alexlarsson** [comment]
Anyway, that looks good to me, although we now need to actually use it :)

**Comment by cgwalters** [comment]
Using it in :arrow_up:

**Comment by alexlarsson** [comment]
Looks good to me, although you could handle the "unknown" case by looking at all sizes, and if say a majority is > 32bit, then assume byte-swapping is needed.

**Comment by cgwalters** [comment]
Yeah, about to do autodetection.

**Comment by cgwalters** [comment]
Now with heuristics :game_die: based on object size in :arrow_up:

**Comment by alexlarsson** [comment]
Another heuristics is to look at the compressed and uncompressed size, and if the compressed is larger, then you probably need to byteswap them.

**Comment by cgwalters** [comment]
For some small files, it's possible that compression makes them larger, as you still need to add a compression header.  But yeah...for these deltas it should really never happen.  Added an implementation in :arrow_up:

**Comment by alexlarsson** [comment]
LGTM

**Comment by cgwalters** [comment]
Merged, thanks!

**Pull request closed without merging**
