### PR TITLE
summary cache

### PR DESCRIPTION
**Pull request by giuseppe**
store a cache of the summary file

https://bugzilla.gnome.org/show_bug.cgi?id=762973

### CODE REVIEW

**Comment by mbarnes** [comment]
Overall LGTM.  Maybe wait for @cgwalters to have a look before merging.

**Comment by cgwalters** [comment]
Overall, I'd say using the signature file as a modification hook is fine, but a better solution (can be in addition) is to properly do [ETag](https://en.wikipedia.org/wiki/HTTP_ETag) like @alexlarsson suggested.  I think this would require integration with fetcher/libsoup.

**Comment by giuseppe** [comment]
fixup patches here :arrow_up:

**Comment by giuseppe** [comment]
I need the file name without the extension `.sig` if present for the lookup in the self->remotes hash table.  If you prefer, I can rewrite it to use just a pointer to set '\0' and then set back its original value.  I used a named buffer as I thought it was more readable (at the expense of some extra copying)

**Comment by giuseppe** [comment]
I can replace it with the following if you prefer:

```
diff --git a/src/libostree/ostree-repo-prune.c b/src/libostree/ostree-repo-prune.c
index c919d5b..3384883 100644
--- a/src/libostree/ostree-repo-prune.c
+++ b/src/libostree/ostree-repo-prune.c
@@ -118,7 +118,6 @@ _ostree_repo_prune_tmp (OstreeRepo *self,
                         GError **error)
 {
   gboolean ret = FALSE;
-  gchar remote[NAME_MAX + 1];
   g_auto(GLnxDirFdIterator) dfd_iter = { 0, };
   glnx_fd_close int fd = -1;
 
@@ -137,7 +136,8 @@ _ostree_repo_prune_tmp (OstreeRepo *self,
 
   while (TRUE)
     {
-      char *suffix;
+      size_t len;
+      gboolean has_sig_suffix = FALSE;
       struct dirent *dent;
 
       if (!glnx_dirfd_iterator_next_dent (&dfd_iter, &dent, cancellable, error))
@@ -146,13 +146,19 @@ _ostree_repo_prune_tmp (OstreeRepo *self,
       if (dent == NULL)
         break;
 
-      g_strlcpy (remote, dent->d_name, sizeof (remote));
-      suffix = g_strstr_len (remote, -1, ".sig");
-      if (suffix)
-        suffix[0] = '\0';
+      len = strlen (dent->d_name);
+      if (len > 4 && g_strcmp0 (dent->d_name + len - 4, ".sig") == 0)
+        {
+          has_sig_suffix = TRUE;
+          dent->d_name[len - 4] = '\0';
+        }
 
-      if (!g_hash_table_contains (self->remotes, remote))
+      if (!g_hash_table_contains (self->remotes, dent->d_name))
         {
+          /* Restore the previous value to get the file name.  */
+          if (has_sig_suffix)
+            dent->d_name[len - 4] = '.';
+
           if (unlinkat (fd, dent->d_name, 0) < 0)
             {
               glnx_set_error_from_errno (error);
```

**Comment by cgwalters** [comment]
Oh right.  Mmm...yeah, hard to make this beautiful.  I'm fine with either way.  Sorry about being overly picky initially.

**Comment by giuseppe** [comment]
rebased and pushed to master.

**Comment by alexlarsson** [comment]
This was broken: https://github.com/GNOME/ostree/pull/204

**Pull request closed without merging**
