### PR TITLE
pull: Handle remote web server not honoring range requests

### PR DESCRIPTION
**Pull request by cgwalters**
It's valid for the remote server to say 200 OK and give us the entire
file instead of a 206 Partial Content, and in that case we should blow
away the previous cached data, rather than blindly appending to it and
thus creating multiple copies of the data inside the file.

This problem primarily occurs when we do have the complete file, and
we're interrupted, then try again, where the new process didn't record
the download was already complete.  We do a range request for bytes
past the end, and some web servers (e.g. Akamai) will return 200 OK
with the whole content again, rather than a 416 Requested Range Not
Satisfiable.

Thus we could also fix this by saner caching strategy - since we know
the file is complete, rename it again to $checksum.done or something
before it's processed.  (Or really, rework how we do caching more
intelligently in general).

This fixes the issue that interrupted pulls failed with such
webservers, although repeated attempts would eventually succeed
because we'd unlink files that failed to pull.

Related: https://bugzilla.redhat.com/show_bug.cgi?id=1207292

### CODE REVIEW

**Comment by mbarnes** [comment]
Looks correct to me.  Little easier to read now too, imo.  :+1:

**Comment by mbarnes** [comment]
I suggest pasting the description above into the commit message for posterity.  Good write up, would like to preserve it in the commit log.

**Comment by cgwalters** [comment]
The pull request description *is* the commit message, no?  Or did you mean the bugzilla?

**Comment by mbarnes** [comment]
Bah, you're right, nevermind.  Brain not completely engaged since the weekend.

**Pull request closed without merging**
