### PR TITLE
giuseppe/tombstone

### PR DESCRIPTION
**Pull request by giuseppe**

### CODE REVIEW

**Comment by giuseppe** [comment]
@mbarnes thanks for all the comments.  I have left the ```tombstone-commits=true``` and didn't change the logic in ostree-repo-traverse.c for now.
If @cgwalters is fine, I would leave tombstone-commits=true instead of a features list, as it is easier to handle and even to read in the config file.

**Comment by cgwalters** [comment]
`tombstone-commits=true` is fine by me yep.

**Comment by cgwalters** [comment]
I like it, thanks!

**Comment by giuseppe** [comment]
I have reworked all the comments, if it fine for you now, I will autosquash the patches and push the series

**Comment by mbarnes** [comment]
LGTM!  :+1:

**Comment by giuseppe** [comment]
pushed thanks!

**Pull request closed without merging**
