### PR TITLE
giuseppe/wip-deltas

### PR DESCRIPTION
**Pull request by giuseppe**
tests are still missing, I will add those once we agree on what is done so far.

I dropped any detached metadata from the static delta files, so no GPG signatures are there.  Instead I added the .sig file for the summary file and list the available delta files there.

### CODE REVIEW

**Comment by giuseppe** [comment]
is there any pending request before this could get closed?  Beside rebase it onto master...

**Comment by cgwalters** [comment]
:+1: from me, WDYT @mbarnes  ?

**Comment by mbarnes** [comment]
Looks good to me.  Couple little niggles but nothing to get in a twist over.

:+1:

**Comment by giuseppe** [comment]
rebased, used the new g_autoptr and pushed!

Thanks for the reviews

**Pull request closed without merging**
