### PR TITLE
Wip/deltas

### PR DESCRIPTION
**Pull request by cgwalters**
A pile of format-breaking changes for deltas.

High level:
 - versioning of delta parts
 - Format now allows streaming
 - Better deduplication

### CODE REVIEW

**Comment by giuseppe** [comment]
I have done some testing on this branch, and I have noticed that some files are missing when I pull a commit which has an --empty static-delta for the last commit.

I am slowly going trough the code changes :-)

(on the origin)
$ sudo ostree static-delta generate --empty --to=88adc396a3688571eb16b284ea7d9134e9cdbce436a32702296ec5779bdbc9b7

(on the second repo)
$ sudo ostree --repo=repo2  init --mode=archive-z2
$ sudo ostree --repo=repo2 remote add  --set=gpg-verify=false master http://localhost:52715
$ sudo ostree --repo=repo2 pull master:master
$ sudo ostree --repo=repo2 fsck (reports missing objects)

**Comment by cgwalters** [comment]
Hmm, I can't reproduce that missing objects bug.  How many are missing?  What content set are you using?

**Comment by giuseppe** [comment]
I am not able to reproduce it anymore with a fresh repo, sorry for the noise; probably something wrong in the source repo I was using.

**Comment by giuseppe** [comment]
except the comment for src/libostree/ostree-repo-prune.c, everything else looks fine for me.

:+1:

**Comment by giuseppe** [comment]
yes, looks good to me.

I have more commits here (to add bsdiff compression): https://github.com/giuseppe/ostree/tree/giuseppe/wip/deltas

**Comment by cgwalters** [comment]
I merged this, let's do further updates in later pulls.

**Pull request closed without merging**
