### PR TITLE
tests: More TAP fixups

### PR DESCRIPTION
**Pull request by cgwalters**
Hopefully getting closer now.

### CODE REVIEW

**Comment by cgwalters** [comment]
Oops, this was in my tree.  Review after commit if desired.

**Comment by jlebon** [comment]
Yes, almost good now. Got a new failure now in `test-basic.sh`:

```
# output
<snip>
PASS: tests/test-basic.sh 48 whiteouts disabled
SKIP: tests/test-basic.sh 49 # SKIP not run when root
ERROR: tests/test-basic.sh - exited with status 1

# relevant test-suite.log section
++ stat '--printf=%Z\n' /var/tmp/tap-test.75JHzz/repo
++ cd ..
++ cmp timestamp-orig.txt timestamp-new.txt
881c324b7ec179fa954ce91470986a36e28c15d6d9034b0ffe3c84acc5fc2702
++ assert_not_reached 'failed to update mtime on repo'
++ echo failed to update mtime on repo
failed to update mtime on repo
++ exit 1
timestamp-orig.txt timestamp-new.txt differ: char 10, line 1
ERROR: tests/test-basic.sh - exited with status 1
```

**Comment by giuseppe** [comment]
is there a way to skip the tests file altogether once the tests plans was printed?  We will probably need that on -o pipefail when the script terminates before all tests run

**Comment by cgwalters** [comment]
I think the only option is to skip each individual test once the plan is printed =/  But can't we structure things so in this case we skip beforehand?

**Comment by cgwalters** [comment]
See https://github.com/GNOME/ostree/pull/201

**Comment by giuseppe** [comment]
I was just thinking when a test fails for any reason, then the error we got from the TAP driver is a bit unclear.  Should we run each test in a subshell so the process doesn't exit immediately?

**Pull request merged**
