### PR TITLE
giuseppe/fix summary crypt

### PR DESCRIPTION
**Pull request by giuseppe**

### CODE REVIEW

**Comment by cgwalters** [comment]
(And what I think would be nice is writing to the local commit in some out of band metadata (xattrs?) a cached version of the signature validation, so you can still know that the commit was transitively signed.  This is nontrivial though)

**Comment by cgwalters** [comment]
Can you take a look at https://github.com/GNOME/ostree/pull/118 and let's land it before we do this?

**Comment by giuseppe** [comment]
I've pushed some new commits.  I've added a gpg-verify-summary option which can be used when gpg-verify is used too.  I had to fix some rebase conflicts, so I pushed again the whole series without fixup commits.

**Comment by giuseppe** [comment]
any comments on the fixups?

**Comment by cgwalters** [comment]
I know you said you were working on it, but didn't realize you'd uploaded new patches - remember there's no notification when you push new changes to a PR, so please add a comment like "Added fixups, please re-review" or so.  Will take a more detailed look soon.

One thing that jumps out at me - the default for gpg-verify-summary has to be `FALSE` if it isn't now, for backwards compatibility.

**Comment by giuseppe** [comment]
I have changed the patches to have ```gpg-verify-summary=FALSE``` by default plus some other cleanups.

**Comment by cgwalters** [comment]
I think this series looks OK now, but I'd like to do another pass with it after the merge is done.

**Pull request closed without merging**
