### PR TITLE
deploy: Also look for /usr/lib/os-release

### PR DESCRIPTION
**Pull request by cgwalters**
With newer versions of systemd, the file has moved there.

### CODE REVIEW

**Comment by mbarnes** [comment]
Seems a little weird using `g_file_load_contents()` for one directory and `g_file_get_contents()` for the other, but otherwise :+1:.

**Comment by cgwalters** [comment]
Yeah, it was ugly...I was trying to do a partial transition away from GFile*.  But let's shave this yak a bit.  I just pushed https://git.gnome.org/browse/libglnx/commit/?id=1ebfefa565692ca033ba2d156c771d9e2c4017fc (post-review on that appreciated btw!)

Then the updated commit here uses it, and IMO it's much prettier, more efficient, etc.

**Comment by mbarnes** [comment]
libglnx post-review: Looks nice.  Using a `GByteArray` in `glnx_fd_readall_malloc()` might shave off a few lines, but... eh.  Not too important.

The updated commit is much cleaner indeed.  :+1: :+1:

**Comment by cgwalters** [comment]
I tried to use a `GString` but it's not really cleaner without a `g_string_ensure_capacity()` or something.  Actually I just filed https://bugzilla.gnome.org/show_bug.cgi?id=744992 to track this.

**Pull request closed without merging**
