### PR TITLE
Giuseppe/rollsum test

### PR DESCRIPTION
**Pull request by giuseppe**

### CODE REVIEW

**Comment by giuseppe** [comment]
@cgwalters, @mbarnes, do these changes make sense to you?

**Comment by mbarnes** [comment]
Still coming up to speed on rolling checksums in general, but the changes here look okay to me.

**Comment by cgwalters** [comment]
Hmm...there's nothing stopping two blocks of different size from having the same CRC!

So I think what we actually need to do here is:

```
if (to_offset != from_offset)
  continue;
```

right?

**Comment by giuseppe** [comment]
True!  I was able to reproduce it with a crafted test case.  Pushed a new commit with the fix and a new test

**Comment by cgwalters** [comment]
Nice test case!  I reworked the branch a little bit so that the bugfix is separate from the tests, to preserve bisectability.  Merged :+1:

**Pull request closed without merging**
